language: objective-c
osx_image: xcode7
before_script:
    - bundle install
script:
    - xcodebuild -project Aardvark.xcodeproj -scheme Aardvark -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build test
    - xcodebuild -project Aardvark.xcodeproj -scheme "Aardvark-iOS" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build
    - pod lib lint --verbose --fail-fast
